DATASET:
    #train_list: ['Human36M', 'PW3D', 'MPII3D', 'COCO', 'MPII']
    train_list: ['Human36M', 'PW3D', 'MPII3D']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 4
    use_gt_input: False

MODEL:
    name: HMR
    embed_dim: 512
    joint_loss_weight: 20
    shape_weight: 0.06
    pose_weight: 60.0
    trans_weight: 0.06

TRAIN:
    batch_size: 8
    shuffle: True
    begin_epoch: 1
    end_epoch: 20
    scheduler: 'step'
    lr: 5e-5
    lr_step: [2, 4, 6, 8, 10, 12, 15]
    lr_factor: 0.95
    optimizer: 'adam'

TEST:
    batch_size: 8
    shuffle: Fasle